# Generated by Django 3.0.5 on 2020-06-23 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_skill', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('code', models.CharField(default='type smth', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('url', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Neutrals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('signup_confirmation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Runes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('code', models.CharField(default='type smth', max_length=18)),
            ],
        ),
        migrations.AddIndex(
            model_name='runes',
            index=models.Index(fields=['name'], name='firstapp_ru_name_9ae7a5_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['lane'], name='firstapp_ro_lane_b9167a_idx'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='neutrals',
            index=models.Index(fields=['name'], name='firstapp_ne_name_e5bca9_idx'),
        ),
        migrations.AddIndex(
            model_name='heroes',
            index=models.Index(fields=['name'], name='firstapp_he_name_1ea4f2_idx'),
        ),
        migrations.AddField(
            model_name='guide',
            name='build_items',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Items'),
        ),
        migrations.AddField(
            model_name='guide',
            name='build_items2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items2', to='firstapp.Items'),
        ),
        migrations.AddField(
            model_name='guide',
            name='build_items3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items3', to='firstapp.Items'),
        ),
        migrations.AddField(
            model_name='guide',
            name='build_items4',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items4', to='firstapp.Items'),
        ),
        migrations.AddField(
            model_name='guide',
            name='build_items5',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items5', to='firstapp.Items'),
        ),
        migrations.AddField(
            model_name='guide',
            name='build_jopa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='jopa', to='firstapp.Runes'),
        ),
        migrations.AddField(
            model_name='guide',
            name='build_neutrals',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Neutrals'),
        ),
        migrations.AddField(
            model_name='guide',
            name='build_neutrals2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='neutrals2', to='firstapp.Neutrals'),
        ),
        migrations.AddField(
            model_name='guide',
            name='build_neutrals3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='neutrals3', to='firstapp.Neutrals'),
        ),
        migrations.AddField(
            model_name='guide',
            name='build_neutrals4',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='neutrals4', to='firstapp.Neutrals'),
        ),
        migrations.AddField(
            model_name='guide',
            name='build_neutrals5',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='neutrals5', to='firstapp.Neutrals'),
        ),
        migrations.AddField(
            model_name='guide',
            name='build_opa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='opa', to='firstapp.Runes'),
        ),
        migrations.AddField(
            model_name='guide',
            name='build_runes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Runes'),
        ),
        migrations.AddField(
            model_name='guide',
            name='heroes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Heroes'),
        ),
        migrations.AddField(
            model_name='guide',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Role'),
        ),
    ]
