# Generated by Django 3.0.5 on 2020-05-19 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('code', models.CharField(default='r5', max_length=18)),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='code',
            field=models.CharField(default='in', max_length=18),
        ),
        migrations.AlterField(
            model_name='guide',
            name='build_runes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Runes'),
        ),
    ]
