# Generated by Django 3.0.5 on 2020-05-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20200519_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='build_summoner_id',
            new_name='build_summoners',
        ),
    ]
