# Generated by Django 3.0.6 on 2020-06-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20200519_1115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Champion',
            new_name='Heroes',
        ),
        migrations.RenameModel(
            old_name='Summoners',
            new_name='Neutrals',
        ),
    ]
