# Generated by Django 3.0.6 on 2020-06-03 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20200603_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='champion',
            new_name='heroes',
        ),
    ]
