# Generated by Django 3.0.6 on 2020-06-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20200603_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='build_summoners',
            new_name='build_neutrals',
        ),
    ]
