# Generated by Django 3.0.6 on 2020-06-04 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20200604_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='build_neutrals2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='neutrals2', to='firstapp.Neutrals'),
        ),
        migrations.AddField(
            model_name='guide',
            name='build_neutrals3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='neutrals3', to='firstapp.Neutrals'),
        ),
        migrations.AddField(
            model_name='guide',
            name='build_neutrals4',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='neutrals4', to='firstapp.Neutrals'),
        ),
        migrations.AddField(
            model_name='guide',
            name='build_neutrals5',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='neutrals5', to='firstapp.Neutrals'),
        ),
        migrations.AlterField(
            model_name='items',
            name='code',
            field=models.CharField(default='type smth', max_length=18),
        ),
        migrations.AlterField(
            model_name='runes',
            name='code',
            field=models.CharField(default='type smth', max_length=18),
        ),
    ]
