# Generated by Django 3.0.6 on 2020-06-04 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20200604_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='build_items',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Items'),
        ),
        migrations.AddField(
            model_name='guide',
            name='build_items2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items2', to='firstapp.Items'),
        ),
        migrations.AddField(
            model_name='guide',
            name='build_items3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items3', to='firstapp.Items'),
        ),
        migrations.AddField(
            model_name='guide',
            name='build_items4',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items4', to='firstapp.Items'),
        ),
        migrations.AddField(
            model_name='guide',
            name='build_items5',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items5', to='firstapp.Items'),
        ),
    ]
